position_mapping = {
    'Managing Consultant': "Manager",
    'Employé anonyme': "Employé anonyme",
    'Senior Consultant': "Consultant",
    'Manager': "Manager",
    'Consultant Confirmé': "Consultant",
    'Consultant': "Consultant",
    'Consultante': "Consultant",
    'Consultant Sénior': "Consultant",
    'Project Manager': "Manager",
    'Consultant Junior': "Consultant",
    'Consultant Senior': "Consultant",
    'Directeur': "Directeur",
    'Partner': "Partner",
    'Consultant Stagiaire': "Stagiaire",
    'Directeur Digital & Solutions': "Directeur",
    'Consultant Confirmée': "Consultant",
    'Ingénieur d affaires': "Consultant",
    'Consultante confirmée': "Consultant",
    'Business Partner': "Partner",
    'Senior Manager': "Manager",
    'Consultante Junior': "Consultant",
    'Consultants senior': "Consultant",
    'Business Developer': "Consultant",
    'Consultant S&eacute; nior': "Consultant",
    'Business Consultant': "Consultant",
    'IT Consultant': "Consultant",
    'Resource Manager': "Manager",
    'Chef De Projet': "Manager",
    'Consultant RGPD': "Consultant",
    'Junior Digital Transformation Consultant': "Consultant",
    'Etudiant En Alternance': "Alternant",
    'Junior Consultant': "Consultant",
    'Chargée De Communication': "Interne"
}
